# Lab3 exercises

### 1) Write a function that returns a column vector from multiple values in input\
example
<pre>
cv(1,2,3)
array([[1],
       [2],
       [3]])
</pre>

### 2) Easier version taking in input an array (not taking into account multiple input parameters)
<pre>
cv([1,4,2])
array([[1],
       [4],
       [2]])
</pre>

### 3) Write a function that takes an array and returns the transpose of the array. You can use 'np.transpose' or the '.T', but you may not use a loop.

### 4) Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays
example
<pre>
a=np.array([1,2,3])
b=np.array([0.74,2.3,3.01])
eqtest(a,b,0.5)
True
</pre>

### 5) Write a NumPy program to test element-wise for NaN of a given array.

### 6) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

### 7) Write a NumPy program to create an array of all the even integers from 30 to 70

### 8) Write a function using NumPy to generate a random number array between 0 and 1
example
<pre>
randzeroone(3)
[0.73434833 0.40929972 0.48984798]
</pre>

### 9)Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

### 10) Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

### 11) Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal like this

      [[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]]

### 12) Create a matrix of 3x3 with numbers from 1 to 9 and extract the array [7,9] using the correct slicing syntax