# Lab3 exercises

### 1) Write a function that returns a column vector from multiple values in input\
example
<pre>
cv(1,2,3)
array([[1],
       [2],
       [3]])
</pre>

### 2) Easier version taking in input an array (not taking into account multiple input parameters)
<pre>
cv([1,4,2])
array([[1],
       [4],
       [2]])
</pre>

### 3) Write a function that takes an array and returns the transpose of the array. You can use 'np.transpose' or the '.T', but you may not use a loop.

### 4) Write a NumPy program to create an element-wise comparison (equal, equal within a tolerance) of two given arrays
example
<pre>
a=np.array([1,2,3])
b=np.array([0.74,2.3,3.01])
eqtest(a,b,0.5)
True
</pre>

### 5) Write a NumPy program to test element-wise for NaN of a given array.

### 6) Write a NumPy program to create an array of 10 zeros,10 ones, 10 fives

### 7) Write a NumPy program to create an array of all the even integers from 30 to 70

### 8) Write a function using NumPy to generate a random number array between 0 and 1
example
<pre>
randzeroone(3)
[0.73434833 0.40929972 0.48984798]
</pre>

### 9)Write a NumPy program to generate an array of 15 random numbers from a standard normal distribution

### 10) Write a NumPy program to create a vector with values ranging from 15 to 55 and print all values except the first and last

### 11) Write a Numpy short program to generate a chess board pattern, expected result is a 2 dimensional array like this
<pre>
array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])</pre>

### 12) Write a NumPy program to create a vector of length 100 with values evenly distributed between -10 and 10

### 13) Write a NumPy program to create a vector with values from 0 to 20 and change the sign of the numbers in the range from 9 to 15

### 14) Write a NumPy program to multiply the values of two given vectors

### 15) Write a NumPy program to create a 3x4 matrix filled with values from 5 to 16

### 16) Write a NumPy program to create a 3x3 identity matrix, i.e. diagonal elements are 1, the rest are 0

### 17) Write a NumPy program to create a 4x4 matrix in which 0 and 1 are staggered, with zeros on the main diagonal like this
<pre>
      [[0, 1, 1, 1],
       [1, 0, 1, 1],
       [1, 1, 0, 1],
       [1, 1, 1, 0]]</pre>

### 18) Write a NumPy program to create a 3x3x3 array filled with arbitrary values


### 19) Write a NumPy program to compute sum of all elements, sum of each column and sum of each row of a given array

### 20) write a npy file containing a 100.000 random values and check its size, then do the same with a normal python list to compare the space used

### 21) Create a matrix of 3x3 with numbers from 1 to 9 and extract the array [7,9] using the correct slicing syntax

### 22) Write a NumPy program to find the closest value (to a given scalar) in an array. 
Original array:\
[ 0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49
50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74
75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]\
Value to compare:\
34.99062268928913\
35